// This file is automatically generated by extra/scripts/generate-language-pack-types.js

import builtinLanguagePack from './english.json';
import specialStringsEnglish from './special-strings/en.json';

type RemoveHash<T extends string, F=T> = T extends `${infer U}#${string}` ? U : F;

export type LanguagePackKey = keyof typeof builtinLanguagePack;

// Applies RemoveHash to all sub-types of LanguagePackKey
export type LanguagePackStringName = RemoveHash<LanguagePackKey>;

export type LanguagePackStringNamePluralized = RemoveHash<LanguagePackKey, never>;

export type LanguagePackSpecialStringName = keyof typeof specialStringsEnglish;

