name: Build and deploy to beta GH pages

on:
  push:
    branches: [main]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout the repository so we can access its contents
    - name: Checkout
      uses: actions/checkout@v2

    # Prepare Node.js
    - name: Use Node.js 15.x
      uses: actions/setup-node@v2
      with:
        node-version: 15.x

    # Create config.js, which stores API ID and hash, log settings and whether to use test cloud or not
    - name: Create config file
      run: 'echo "export function getCredentials() {return {api_id: ${{ secrets.API_ID }},api_hash: ${{ secrets.API_HASH }}};}export function getConfig() {return {use_test_dc: false,log: {log_updates: true,log_queries: true}};}" > ./src/dibgram/TdWeb/config.js'
      shell: bash

    # Install all dependencies defined in package.json
    - name: Install dependencies
      run: npm ci

    # Create an optimized build
    - name: Build
      run: npm run build --if-present
      env:
        CI: false

    # Deploy to GitHub Pages
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.3.0
      if: success()
      with:
        keep_history: true
        build_dir: build
        repo: DIBgram/beta
        target_branch: main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_PAT: ${{ secrets.REPO_WRITE_PAT }}
