# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Production Build

on:
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Create config file
      run: 'echo "export function getCredentials() {return {api_id: $APIID,api_hash: $APIHASH};}export function getConfig() {return {use_test_dc: false,log: {log_updates: false,log_queries: false}};}" > ./src/dibgram/TdWeb/config.js'
      shell: bash
      env:
        APIID: ${{ secrets.API_ID }}
        APIHASH: ${{ secrets.API_HASH }}
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build --if-present
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.3.0
      if: success()
      with:
        keep_history: true
        # Build directory to deploy
        build_dir: build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
