# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Production Build

on:
  workflow_dispatch:
    inputs:
      use_test_dc:
        description: "Use Telegram's test servers (only true/false)"
        required: false
        default: 'false'
      log_queries:
        description: "Log TdLib queries (only true/false)"
        required: false
        default: 'false'
      log_updates:
        description: "Log TdLib updates (only true/false)"
        required: false
        default: 'false'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 15.x
      uses: actions/setup-node@v2
      with:
        node-version: 15.x
    - name: Create config file
      run: 'echo "export function getCredentials() {return {api_id: ${{ secrets.API_ID }},api_hash: ${{ secrets.API_HASH }}};}export function getConfig() {return {use_test_dc: ${{ github.event.inputs.use_test_dc }},log: {log_updates: ${{ github.event.inputs.log_updates }},log_queries: ${{ github.event.inputs.log_queries }}}};}" > ./src/dibgram/TdWeb/config.js'
      shell: bash
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build --if-present
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-results
        path: build
